# Generated by Django 6.0.7 on 2026-07-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='earning',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='invest',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['name', 'id']},
        ),
    ]
