# Generated by Django 6.0.7 on 2026-07-20 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('network', '0002_router'),
        ('onu', '0002_alter_onu_options'),
        ('pop', '0002_alter_pop_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(help_text='Human-facing account number shown to the customer.', max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('nid', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('connection_type', models.CharField(choices=[('pppoe', 'PPPoE'), ('static_ip', 'Static IP')], max_length=20)),
                ('pppoe_username', models.CharField(blank=True, help_text='Unique across the whole system, not per router, so a subscriber cannot exist twice.', max_length=64, null=True, unique=True)),
                ('pppoe_password_enc', models.BinaryField(default=b'')),
                ('static_ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', unique=True)),
                ('mac_address', models.CharField(blank=True, help_text='Optional ARP binding for static-IP subscribers.', max_length=17)),
                ('service_state', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('grace', 'Grace'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='pending', help_text='Never assign directly — go through apps.subscribers.services.transition().', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='When paid service ends. NULL never expires — migrated subscribers have no source data for this and must not be suspended until a payment sets it.', null=True)),
                ('grace_days', models.PositiveIntegerField(default=3, help_text='Days of service after expiry before suspension.')),
                ('auto_renew', models.BooleanField(default=True)),
                ('sync_state', models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending'), ('drifted', 'Drifted'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('onu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='onu.onu')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscribers', to='billing.package')),
                ('pop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='pop.pop')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscribers', to='network.router')),
            ],
            options={
                'ordering': ['-created', '-id'],
                'indexes': [models.Index(fields=['service_state', 'expires_at'], name='subscribers_service_67be5e_idx'), models.Index(fields=['sync_state'], name='subscribers_sync_st_578ae8_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('connection_type', 'pppoe'), _negated=True), ('pppoe_username__isnull', False), _connector='OR'), name='pppoe_requires_username'), models.CheckConstraint(condition=models.Q(models.Q(('connection_type', 'static_ip'), _negated=True), ('static_ip__isnull', False), _connector='OR'), name='static_requires_ip')],
            },
        ),
    ]
