# Generated by Django 6.0.7 on 2026-07-20 08:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('download_kbps', models.PositiveIntegerField(help_text='Subscriber download rate in kbps.', validators=[django.core.validators.MinValueValidator(1)])),
                ('upload_kbps', models.PositiveIntegerField(help_text='Subscriber upload rate in kbps.', validators=[django.core.validators.MinValueValidator(1)])),
                ('burst_download_kbps', models.PositiveIntegerField(blank=True, null=True)),
                ('burst_upload_kbps', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('billing_cycle_days', models.PositiveIntegerField(default=30, help_text='Days of service one payment buys.', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True, help_text='Inactive packages cannot be assigned to new subscribers.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['download_kbps', 'name', 'id'],
            },
        ),
    ]
