# Generated by Django 6.0.7 on 2026-07-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['speed', 'name', 'id']},
        ),
    ]
