# Generated by Django 6.0.7 on 2026-07-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['-created', '-id']},
        ),
        migrations.AlterModelOptions(
            name='warehousecategory',
            options={'ordering': ['name', 'id']},
        ),
    ]
