# Generated by Django 6.0.7 on 2026-07-20 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_automatic', models.BooleanField(default=False)),
                ('subject_type', models.CharField(max_length=50)),
                ('subject_id', models.IntegerField()),
                ('subject_label', models.CharField(blank=True, help_text='Human-readable subject at the time, kept for when the subject is later deleted or renamed.', max_length=200)),
                ('action', models.CharField(max_length=50)),
                ('state_before', models.CharField(blank=True, max_length=30)),
                ('state_after', models.CharField(blank=True, max_length=30)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('succeeded', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null when the action was automatic.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['subject_type', 'subject_id', '-created_at'], name='network_ser_subject_a101fa_idx'), models.Index(fields=['action', '-created_at'], name='network_ser_action_c13395_idx')],
            },
        ),
    ]
