# Generated by Django 6.0.7 on 2026-07-20 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
        ('pop', '0002_alter_pop_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('host', models.GenericIPAddressField(protocol='IPv4')),
                ('api_port', models.PositiveIntegerField(default=8728, help_text='8728 for plain API, 8729 for API-SSL.')),
                ('use_tls', models.BooleanField(default=False, help_text='Use API-SSL. Strongly preferred — plain API sends the password in the clear.')),
                ('username', models.CharField(max_length=100)),
                ('password_enc', models.BinaryField(default=b'')),
                ('routeros_version', models.CharField(blank=True, max_length=30)),
                ('board_name', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('reachable', 'Reachable'), ('unreachable', 'Unreachable'), ('auth_failed', 'Auth failed')], default='unknown', max_length=20)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('dry_run', models.BooleanField(default=True, help_text='When on, provisioning logs what it would write instead of writing it. Defaults on so a newly added router cannot be modified by accident.')),
                ('enabled', models.BooleanField(default=True, help_text='Disabled routers are skipped by polling and provisioning.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routers', to='pop.pop')),
            ],
            options={
                'ordering': ['name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('host', 'api_port'), name='unique_router_endpoint')],
            },
        ),
    ]
